---
- hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
  
  tasks:
    - import_tasks: tasks/cli.yml
      name: Install command line utilities
      tags: ['cli']
