---
- hosts: all

  vars_files:
    - default.config.yml
    - config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      tags: ['mas']

  tasks:
    - name: node
      import_tasks: tasks/node.yml
      tags: ['cli', 'node']
    - name: node
      import_tasks: tasks/python.yml
      tags: ['cli', 'python']
