---
- hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']

  tasks:
    - include: tasks/node.yml
      tags: ['cli', 'node']
    - include: tasks/python.yml
      tags: ['cli', 'python']
