
---
- name: Install volta
  shell: curl https://get.volta.sh | bash
  args:
    creates: $HOME/.volta/bin/volta

- name: Install node clis
  shell: volta install {{ item }}
  loop:
      - node
      - yarn
  args:
    creates: $HOME/.volta/bin/{{ item }}

- name: Install node binaries
  shell: npm install -g {{ item.name }}
  loop:
      - name: typescript
        bin: tsc
      - name: trash-cli
        bin: trash
      - name: aicommits
        bin: aicommits
      - name: "@githubnext/github-copilot-cli"
        bin: github-copilot-cli
  args:
    creates: $HOME/.volta/bin/{{ item.bin }}
